---
name: Build
on:
  push:
    branches:
      - develop

  workflow_dispatch:
env:
  IMAGE_NAME: temp-intermediate-docker-cache
  VERSION_NUMBER: '1.0.1.${{ github.run_number }}'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Build image
        env:
          #@@@ RENAME IMAGE
          BUILDER_IMAGE_ID: ghcr.io/${{ github.repository_owner }}/temp-intermediate-docker-cache-builder
          DOCKER_IMAGE_NAME: ${{ env.IMAGE_NAME }}
        run: |
          set -euxo pipefail

          # Log into Github container registry for building image
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

          # Pull previous builder image
          #@@@ REMOVE "|| true"?
          docker pull "$BUILDER_IMAGE_ID" || true

          # Build new builder image
          docker build -f Dockerfile.builder -t "$BUILDER_IMAGE_ID" \
            --cache-from "$BUILDER_IMAGE_ID" .

          # Build website image
          docker build . -t "$DOCKER_IMAGE_NAME"

          # Tag website image with version
          docker tag "$DOCKER_IMAGE_NAME" "$DOCKER_IMAGE_NAME:$VERSION_NUMBER"

          # Push images
          docker push "$BUILDER_IMAGE_ID"
          #@@@ docker push "$DOCKER_IMAGE_NAME"
          #@@@ docker push "$DOCKER_IMAGE_NAME:$VERSION_NUMBER"
